production:
  solr: &solr-prod
    hostname: solr
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    <<: *solr-prod
    log_level: INFO
    path: /solr/development

test:
  solr:
    <<: *solr-prod
    hostname: localhost
    path: /solr/test
    
